# Generated by Django 4.0.4 on 2022-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
