# Generated by Django 3.2.9 on 2022-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0002_events_event_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
