# Generated by Django 4.0.4 on 2022-05-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0003_countimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='countimage',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
