# Generated by Django 4.0.4 on 2022-05-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0004_countimage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='countimage',
            name='Event_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
